#!/usr/bin/env php
<?php

/*
 * --------------------------------------------------------------------
 * CodeIgniter command-line tools
 * --------------------------------------------------------------------
 * The main entry point into the CLI system and allows you to run
 * commands and perform maintenance on your application.
 *
 * Because CodeIgniter can handle CLI requests as just another web request
 * this class mainly acts as a passthru to the framework itself.
 */

define('SPARKED', true);

/*
 *---------------------------------------------------------------
 * BOOTSTRAP THE APPLICATION
 *---------------------------------------------------------------
 * This process sets up the path constants, loads and registers
 * our autoloader, along with Composer's, loads our constants
 * and fires up an environment-specific bootstrapping.
 */

// Refuse to run when called from php-cgi
if (substr(php_sapi_name(), 0, 3) === 'cgi')
{
	die("The cli tool is not supported when running php-cgi. It needs php-cli to function!\n\n");
}

// Path to the front controller (for CLI, this is the project root)
define('FCPATH', __DIR__ . DIRECTORY_SEPARATOR);

// Load our paths config file
require 'app/Config/Paths.php';
// ^^^ Change this line if you move your application folder

$paths = new Config\Paths();

// Define path constants
define('APPPATH', realpath($paths->appDirectory) . DIRECTORY_SEPARATOR);
define('SYSTEMPATH', realpath($paths->systemDirectory) . DIRECTORY_SEPARATOR);
define('ROOTPATH', realpath(FCPATH) . DIRECTORY_SEPARATOR);
define('WRITEPATH', realpath($paths->writableDirectory) . DIRECTORY_SEPARATOR);

// Define environment
if (is_file(ROOTPATH . '.env')) {
    $env = parse_ini_file(ROOTPATH . '.env');
    if (isset($env['CI_ENVIRONMENT'])) {
        define('ENVIRONMENT', $env['CI_ENVIRONMENT']);
    } else {
        define('ENVIRONMENT', 'development');
    }
} else {
    define('ENVIRONMENT', 'development');
}

// Ensure the current directory is pointing to the front controller's directory
chdir(FCPATH);

/*
 * ---------------------------------------------------------------
 * LOAD COMPOSER AUTOLOADER
 * ---------------------------------------------------------------
 */
require_once ROOTPATH . 'vendor' . DIRECTORY_SEPARATOR . 'autoload.php';

/*
 * ---------------------------------------------------------------
 * LOAD CONSTANTS AND FRAMEWORK
 * ---------------------------------------------------------------
 */

// Load app constants
if (is_file(APPPATH . 'Config' . DIRECTORY_SEPARATOR . 'Constants.php')) {
    require_once APPPATH . 'Config' . DIRECTORY_SEPARATOR . 'Constants.php';
}

// Load system functions
require_once SYSTEMPATH . 'Common.php';

// Load our autoloader and register it
require_once SYSTEMPATH . 'Config' . DIRECTORY_SEPARATOR . 'AutoloadConfig.php';
require_once APPPATH . 'Config' . DIRECTORY_SEPARATOR . 'Autoload.php';
require_once APPPATH . 'Config' . DIRECTORY_SEPARATOR . 'Modules.php';

$loader = \CodeIgniter\Config\Services::autoloader();
$loader->initialize(new \Config\Autoload(), new \Config\Modules());
$loader->register();

$app = \Config\Services::codeigniter();

// Grab our Console
$console = new \CodeIgniter\CLI\Console($app);

// We want errors to be shown when using it from the CLI.
error_reporting(-1);
ini_set('display_errors', 1);

// Show basic information before we do anything else.
$console->showHeader();

// fire off the command in the main framework.
$exitCode = $console->run();
exit($exitCode);
